NUM_FONT = 50
SKETCH_FONT = 35
TIMER_FONT = 30
RULES_FONT = 22
BOARD_SIZE = 750
TIMER_HEIGHT = 50
SIDE_PANEL_WIDTH = 220
LEADERBOARD_PANEL_WIDTH = 220
GAME_HEIGHT = BOARD_SIZE + TIMER_HEIGHT
GAME_WIDTH = SIDE_PANEL_WIDTH + BOARD_SIZE + LEADERBOARD_PANEL_WIDTH
BOARD_X_OFFSET = SIDE_PANEL_WIDTH
RIGHT_PANEL_X = BOARD_X_OFFSET + BOARD_SIZE
HINT_BUTTON_RECT = (25, 85, 160, 44)
HINT_PENALTY_SECONDS = 15
RULES_BOX_RECT = (15, 155, 190, 295)
LEADERBOARD_BOX_RECT = (RIGHT_PANEL_X + 15, 85, 190, 230)
WIN_MODAL_WIDTH = 430
WIN_MODAL_HEIGHT = 270
WIN_MODAL_X = (GAME_WIDTH - WIN_MODAL_WIDTH) // 2
WIN_MODAL_Y = (GAME_HEIGHT - WIN_MODAL_HEIGHT) // 2
WIN_MODAL_RECT = (WIN_MODAL_X, WIN_MODAL_Y, WIN_MODAL_WIDTH, WIN_MODAL_HEIGHT)
NAME_INPUT_RECT = (WIN_MODAL_X + 65, WIN_MODAL_Y + 132, WIN_MODAL_WIDTH - 130, 38)
WIN_SUBMIT_BUTTON_RECT = (WIN_MODAL_X + 135, WIN_MODAL_Y + 195, 160, 42)
DEFAULT_REMOVED_CELLS = 30
DIFFICULTY_REMOVED_CELLS = {
    "easy": 30,
    "medium": 40,
    "hard": 50,
}
BG_COLOR = (252, 248, 235)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
BLOCK_SIZE = BOARD_SIZE / 9
